
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make box-build'
	@echo
	@echo '	$$ make box-run'
	@echo '	$$ make box-run-portal'
	@echo
.PHONY: help




box-build:
	./box-build.sh
.PHONY: box-build




box-run:
	./box-run.sh
.PHONY: box-run


box-run-portal:
	./box-run-portal.sh
.PHONY: box-run-portal
