
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make box-build'
	@echo '	$$ make box-run'
	@echo
	@echo '	$$ make master-build'
	@echo
.PHONY: help




box-build:
	./box-build.sh
.PHONY: box-build


box-run:
	./box-run.sh
.PHONY: box-run


master-build:
	./master-build.sh
.PHONY: master-build
